[package]
name = "front_matter"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "=0.6.12"
serde = { version = "=1.0.219", features = ["derive"] }
toml = "=0.8.22"

[dev-dependencies]
walkdir = "=2.5.0"
